app/importers/trade_event/ustda_data.rb

Trade Events: USTDA endpoint is empty

---

app/importers/trade_event/sba_data.rb

SBA trade events ssl connection error on production

---

app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb

Developers see new confirmation instrux

---

app/models/user.rb
spec/lib/query_spec.rb
spec/models/user_spec.rb
spec/support/users.rb

Developers must enter min 8 characters 1 alpha to register

---

lib/searchable.rb
spec/lib/searchable_spec.rb

Allow "callback" param for JSONP users.

---

app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb

Place user management error messages above form

---

app/assets/stylesheets/customizations.css.scss
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
spec/models/user_spec.rb

https://www.pivotaltracker.com/n/projects/1085558/stories/92466844

API keys verbage

---

app/controllers/api_controller.rb
lib/query.rb
spec/controllers/api_controller_spec.rb
spec/lib/query_spec.rb

I want to verify if you feel comfortable adding Rack middlewares!
P.S, currently tests will not cover the middleware, we need to add integration tests https://stackoverflow.com/questions/5016690/making-rails-tests-aware-of-rack-middleware-outside-railss-internal-chain

Negative offset handling 

---

app/controllers/registrations_controller.rb
spec/controllers/api/registrations_controller_spec.rb
spec/spec_helper.rb

/regenerate_api_key 401s if user not logged in.

---

app/models/user.rb
config/initializers/devise.rb
spec/models/user_spec.rb

Adds user account locking.

---

app/importers/emenu_bsp_data.rb
app/models/emenu_bsp.rb
app/queries/emenu_bsp_query.rb
spec/api/v1/emenu_bsps/all_results.json
spec/api/v1/emenu_bsps/one_match.json
spec/api/v2/emenu_bsps/all_results.json
spec/api/v2/emenu_bsps/one_match.json
spec/importers/emenu_bsp/emenu_bsp_articles.yaml
spec/queries/emenu_bsp/search_body_with_filters.json

Ok, this has HTML sanitization, `contact_name` added to indexing, and generating our own `id`.

Emenu BSP - IDs, index contact_name, sanitize.

---

deploy/after_restart.rb

Create new indices during deploy

---

app/helpers/nav_helper.rb
app/views/layouts/_topbar.html.erb

@jamesisaacs I just moved over the navigation updates for the API Key page.

updated navigation for developer portal

---

lib/tasks/ita.rake

https://www.pivotaltracker.com/story/show/103358358

Don't attempt to import if importer is disabled

---

README.md
lib/tasks/db.rake

- Changed db:drop task to only nuke webservices indexes
- Updated README to reflect steps I took to get up and running

Update setup instructions for devs not using Docker

---

app/models/trade_event/consolidated.rb
spec/api/v1/trade_events/consolidated_spec.rb
spec/api/v1/trade_events/exim_spec.rb
spec/api/v2/trade_events/consolidated_spec.rb
spec/support/trade_events_search_behavior.rb

https://www.pivotaltracker.com/story/show/104442578

Commment EXIM out for the time-being

---

app/views/layouts/_topbar.html.erb

related story: https://www.pivotaltracker.com/story/show/101998848

added new page

---

app/models/data_source.rb
spec/api/v2/api_models_controller_spec.rb
spec/models/data_source_spec.rb

- Added restrictions on the data source's api field
- rubocop'd api_models_controller_spec

[#108246040] Blank screen on Endpoint Me!

---

app/assets/stylesheets/application.css.scss
app/helpers/nav_helper.rb
app/views/layouts/_header.html.erb
app/views/layouts/_topbar.html.erb
spec/helpers/nav_helper_spec.rb

Reverts GovWizely/webservices#261

Revert "new navigation and styles"

---

app/controllers/data_sources_controller.rb
app/models/data_source.rb
app/views/data_sources/_form.html.haml
app/views/data_sources/new.html.haml
lib/ext/hash.rb
spec/features/data_source_spec.rb
spec/fixtures/data_sources/updated_de_minimis_date.csv

[#109757388] Admins can upload new version of CSV dataset to existing endpoint

---

README.md
app/models/user.rb
config/application.rb
config/routes.rb
lib/tasks/dev.rake
spec/models/user_spec.rb

- Update README to reflect new functionality
- Remove hardcoded company names

[#113859475] make README and admin user more generic

---

app/importers/data_sources/external_mapping_transformation.rb
app/importers/data_sources/reformat_date_transformation.rb
app/importers/data_sources/string_transformation.rb
app/importers/data_sources/transformer.rb
app/models/data_source.rb
lib/ext/string.rb
spec/cassettes/importers/data_sources/external_mapping_transformation/ivory_coast_yml.yml
spec/cassettes/importers/data_sources/external_mapping_transformation/nope_yml.yml
spec/models/data_sources/transformer_spec.rb

- Added ExternalMappingTransformation
- Refactored ReformatDate into its own transformation class.
- Removed redundant call to refresh_index! from data_source.rb

[#110202354] Endpointme admin can leverage external APIs to map field values

---

Gemfile

[#117561565] Fix/remove Airbrake from environments where it's not configured

---

app/importers/data_sources/external_mapping_transformation.rb
app/importers/data_sources/metadata.rb
app/queries/api_model_query.rb
lib/cached_api_endpoint.rb
lib/param_encoder.rb
lib/query.rb
lib/semantic_query_service.rb
spec/cassettes/importers/data_sources/semantic_query_service/brazil_yml.yml
spec/cassettes/importers/data_sources/semantic_query_service/request_yml.yml
spec/fixtures/data_sources/sqs.json
spec/fixtures/data_sources/sqs.yaml
spec/lib/param_encoder_spec.rb
spec/lib/query/search_body_with_all.json
spec/lib/query_spec.rb
spec/lib/semantic_query_service_spec.rb
spec/models/data_source_spec.rb
spec/queries/ita_office_location/search_body_with_match_city.json

[#125046091] admins can specify query preprocessor

---

app/models/concerns/indexable.rb
app/models/concerns/searchable.rb

I deleted the two code branches instead of writing test coverage for
them, as I'm not sure they ever get executed in production either
Context:
https://github.com/GovWizely/webservices/pull/154/commits/ec3607a3723d8b66f649398932280bba9f40aa16
https://github.com/GovWizely/webservices/pull/154/commits/f437a2cea9cfbabba44b0b33f724db94ea421cba

[#116736649] Get test coverage back to 100%

---

app/models/screening_list/score_adjuster.rb
spec/models/screening_list/score_adjuster_spec.rb

when some results are not highlighted

[#133219629] CSL search with fuzzy_name=true returns error 500 

---

lib/parsers/data_sources/xml_parser.rb
spec/fixtures/data_sources/posts.xml

[#134855517] Fix CSV parsing error

---

app/importers/screening_list/isa_data.rb
app/models/screening_list/consolidated.rb
app/models/screening_list/isa.rb
app/views/api/v2/screening_lists/isa/_entry.json.jbuilder
app/views/api/v2/screening_lists/isa/default/_entry.json.jbuilder
app/views/api/v2/screening_lists/isa/search.json.jbuilder
app/views/api/v2/screening_lists/isa/vessel/_entry.json.jbuilder
lib/index_monitor.rb
spec/api/v2/screening_lists/consolidated_spec.rb
spec/api/v2/screening_lists/isa_spec.rb
spec/cassettes/importers/screening_list/isa_yml.yml
spec/fixtures/screening_lists/treasury_consolidated/consolidated.xml
spec/importers/screening_list/fse/results.yaml
spec/importers/screening_list/isa/results.yaml
spec/importers/screening_list/isa_data_spec.rb
spec/models/screening_list/consolidated_spec.rb
spec/support/screening_lists/fse/expected_results.json
spec/support/screening_lists/isa/expected_results.json
spec/support/screening_lists_search_behavior.rb

Reverts GovWizely/webservices#412

Revert "Remove ISA from CSL"

---

app/importers/screening_list/eo13599_data.rb
app/models/screening_list/consolidated.rb
app/models/screening_list/eo13599.rb
app/views/api/v2/screening_lists/13599/_entry.json.jbuilder
app/views/api/v2/screening_lists/13599/default/_entry.json.jbuilder
app/views/api/v2/screening_lists/13599/search.json.jbuilder
app/views/api/v2/screening_lists/13599/vessel/_entry.json.jbuilder
lib/index_monitor.rb
spec/api/v2/screening_lists/consolidated_spec.rb
spec/api/v2/screening_lists/eo13599_spec.rb
spec/cassettes/importers/screening_list/eo13599_yml.yml
spec/importers/screening_list/eo13599/results.yaml
spec/models/screening_list/consolidated_spec.rb
spec/support/screening_lists/eo13599/expected_results.json
spec/support/screening_lists_search_behavior.rb

Importer spec for source to be added later [#150235169]

Add new CSL source - Eo13599

---

app/views/layouts/application.html.erb

Reverts GovWizely/webservices#423

Revert "[EDSP-284] Add shutdown notice"

---

app/views/layouts/_topbar.html.erb

Reverts GovWizely/webservices#437

Revert "Add shutdown notice"
